version: '3'

services:
  # MySQL
  db:
    container_name: alurafood-mysql8
    image: mysql:8.0
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: alurafood
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: alurafood-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./dados:/var/lib/rabbitmq/
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
volumes:
  mysql-volume:
    driver: local